name: stdlog
description: A wrapper around the built-in stdio IOSinks using the KISS principle.
version: 1.0.3
repository: https://github.com/tytydraco/stdlog

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  very_good_analysis: ^3.0.1

dependencies:
  stack_trace: ^1.10.0
